### ISSUE TITLE
Cambiar el título de PYCON PANAMA 2024 en la página web

### ISSUE THREAD

**Issue by yosef7** [pythonpanama/pycon_panama#5]
Necesitamos cambiar el título de "PYCON PANAMA 2024" en la página web [https://www.pythonpanama.org](https://www.pythonpanama.org/)
Debe tener el titulo solamente de: PYCON PANAMÁ

**Tareas:**
- [x] Actualizar el título en la página principal
- [x] Publicar la actualización en el sitio web

**Comment by NiozMaster** [comment]
Ya he aplico este cambio fue desplegada en vercel
