### ISSUE TITLE
Crear una sección de patrocinadores

### ISSUE THREAD

**Issue by yosef7** [pythonpanama/pycon_panama#6]
Necesitamos crear una sección adicional en la página web de PyCon Panamá para destacar a nuestros patrocinadores.

**Tareas:**
- [x] Diseñar la sección de patrocinadores
- [x] Revisar, añadir las imágenes ([PSF](https://wiki.python.org/psf/PSF%20Press%20Kit)) 
- [x] Publicar la actualización en el sitio web

**Comment by NiozMaster** [comment]
Ya esta visible en el sitio web la sección del patrocinadores, según lo solicitado.
link: [PyCon Panamá](https://www.pycon.pa/)
